### ISSUE TITLE
duplicated snippets because of internal error

### ISSUE THREAD

**Issue by depaolim** [django-de/djangosnippets.org#34]
I got this error
"There's been an internal error on the server; it probably wasn't anything you did, so don't worry too much about it. The site administrators have been emailed with the details, and they'll probably get it fixed real soon."

So I retried the operation

The result is I have multiple duplicated snippets
But I can't remove the duplicates

https://djangosnippets.org/users/depaolim/

Please remove the duplicates and possibly add a remove-button available to the user

**Comment by jezdez** [comment]
Yeah, the earch was broken but works now again. Sorry for the problems!
