### ISSUE TITLE
old snippet of mine only accessible through direct link (and causes other weird issues)

### ISSUE THREAD

**Issue by yuvii** [django-de/djangosnippets.org#36]
About a year ago, I uploaded a snippet to the site. I wanted to find it today to use for a project, but couldn't find it through the search. So I logged in (it required confirmation again - which was weird, but reasonable considering I haven't visited in a long while). I couldn't find it. I kept looking and nothing.

Luckily, I had saved the link somewhere, so I fished it out. Here it is:
https://djangosnippets.org/snippets/3019/

So the snippet does exist! However, trying to bookmark it (for example) returns an error. I'm guessing other operations won't work either.

**Comment by jezdez** [comment]
The search was broken and triggered all those errors. Can you try again?

**Comment by yuvii** [comment]
@jezdez 
Seems to be fixed. Thank you! :smile:
